CREATE TABLE capture (
    id BIGINT NOT NULL AUTO_INCREMENT,
    state INTEGER NOT NULL DEFAULT 0,
    url TEXT,
    started TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status INTEGER,
    reason TEXT,
    size BIGINT,
    PRIMARY KEY (id)
);